// This file is auto-generated by Supabase.
// Do not edit it manually.
//
// You can generate this file by running `npx supabase gen types typescript --project-id <your-project-id> > src/lib/supabase/database.types.ts`

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      menu_items: {
        Row: {
          id: string
          name: string
          description: string
          price: number
          category: string
          image_url: string
          is_available: boolean
        }
        Insert: {
          id?: string
          name: string
          description: string
          price: number
          category: string
          image_url: string
          is_available?: boolean
        }
        Update: {
          id?: string
          name?: string
          description?: string
          price?: number
          category?: string
          image_url?: string
          is_available?: boolean
        }
        Relationships: []
      }
      order_items: {
        Row: {
          id: string
          order_id: string
          menu_item_id: string
          quantity: number
          price: number
        }
        Insert: {
          id?: string
          order_id: string
          menu_item_id: string
          quantity: number
          price: number
        }
        Update: {
          id?: string
          order_id?: string
          menu_item_id?: string
          quantity?: number
          price?: number
        }
        Relationships: [
          {
            foreignKeyName: "order_items_menu_item_id_fkey"
            columns: ["menu_item_id"]
            referencedRelation: "menu_items"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "order_items_order_id_fkey"
            columns: ["order_id"]
            referencedRelation: "orders"
            referencedColumns: ["id"]
          }
        ]
      }
      orders: {
        Row: {
          id: string
          customer_name: string
          total: number
          status: "New" | "Preparing" | "Ready for Pickup" | "Completed" | "Cancelled"
          order_time: string
        }
        Insert: {
          id?: string
          customer_name: string
          total: number
          status?: "New" | "Preparing" | "Ready for Pickup" | "Completed" | "Cancelled"
          order_time?: string
        }
        Update: {
          id?: string
          customer_name?: string
          total?: number
          status?: "New" | "Preparing" | "Ready for Pickup" | "Completed" | "Cancelled"
          order_time?: string
        }
        Relationships: []
      }
    }
    Views: { [_ in never]: never }
    Functions: { [_ in never]: never }
    Enums: {
      order_status: "New" | "Preparing" | "Ready for Pickup" | "Completed" | "Cancelled"
    }
    CompositeTypes: { [_ in never]: never }
  }
}
